STAC harmonization changes
opengeospatial/ogcapi-records pull request #236
Opened 2023-04-26 03:56 UTC by pvretano

Numerous changes listed in issue #178 to bring OARec and STAC into closer alignment.

Closes #178

2023-04-26 04:28 UTC, pvretano commented
Closes #232

2023-04-26 08:12 UTC, tomkralidis requested changes

2023-04-26 08:12 UTC, tomkralidis commented on core/openapi/schemas/time.yaml
> +  properties:
Can we add `resolution` as an optional property?

```yaml
      resolution:
        description: |-
          Minimum time period resolvable in the dataset, as an ISO 8601 duration
          type: string
```

See #147/#149

2023-04-27 11:59 UTC, pvretano commented on core/openapi/schemas/time.yaml
> +- type: 'null'
Fixed.

2023-04-27 12:37 UTC, kalxas approved these changes

2023-04-27 14:50 UTC, cnreediii commented
@tomkralidis what does resolution mean in this context? Thnx

2023-05-02 02:21 UTC, merged