Patch OpenAPI example ...
opengeospatial/ogcapi-records pull request #329
Opened 2023-12-30 04:13 UTC by pvretano

Patch OpenAPI building blocks file and example.  Convert all instances of "catalogue" to "catalog".

Closes #309

2023-12-30 22:58 UTC, tomkralidis requested changes

2023-12-30 22:58 UTC, tomkralidis commented on core/openapi/schemas/schema.yaml
Do we need the OpenAPI schema itself here?

2023-12-30 23:00 UTC, pvretano commented on core/openapi/schemas/schema.yaml
Yup ... the list of sortables is a list of schema fragments that describe each sortable.  I suppose we could just say `"type": "object"` and simply say that the object has to be a schema fragment.

2024-01-01 17:26 UTC, tomkralidis approved these changes

2024-01-02 09:49 UTC, kalxas approved these changes

2024-01-02 09:49 UTC, merged